SRCS	=	push_swap_parsing.c lichains_utils.c commands_1.c

MAIN	=	push_swap.c

HEADERS	= 	../libft/libft.a push_swap.h

CC		= 	gcc -g -Wall -Wextra -Werror

all	:
			$(CC) $(SRCS) $(MAIN) $(HEADERS)
			@echo "Files compiled"
