SRCS	=	push_swap_parsing.c commands_1.c commands_2.c commands_3.c list_utils.c \
			solver.c solver_utils.c

MAIN	=	push_swap.c

HEADERS	= 	../libft/libft.a push_swap.h

CC		= 	gcc -g -Wall -Wextra -Werror

all	:
			$(CC) $(SRCS) $(MAIN) $(HEADERS)
			@echo "Files compiled"
